# Generated by Django 4.0.6 on 2022-08-03 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'System',
            },
        ),
        migrations.CreateModel(
            name='testRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNumber', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('requester', models.CharField(max_length=10)),
                ('requestDate', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('docStatus', models.CharField(max_length=100)),
                ('attachment', models.BooleanField(default=False)),
                ('approver', models.CharField(max_length=10)),
                ('detailUrl', models.URLField(blank=True, null=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skcone_web.system')),
            ],
            options={
                'verbose_name_plural': 'testRequest',
                'ordering': ['requestDate'],
            },
        ),
    ]
